### PR TITLE
Google Analytics

### PR DESCRIPTION
**Pull request by samuele-mattiuzzo**
Both in `production.rb` and `staging.rb` we have now a check, based on the existence of the `ENV` variable. This allows us to have 2 separate GA tracking codes as well as turn the functionality on / off on a per instance basis (all we need to do is delete the flag). The functionality can also go live as-is till the GA is set up properly at account level.

Pretty simple and straight forward.

### CODE REVIEW

**Review by SuttonMashing — COMMENTED** [review]
Add secrets to sidekiq and CF in app. Make secrets in Github.

**Review by neilkidd — APPROVED** [review]
LGTM
1 question @samuele-mattiuzzo - the ENV vars aren't set in the webapp in staging but are for sidekiq. Is that correct?

**Comment by samuele-mattiuzzo** [comment]
> LGTM 1 question @samuele-mattiuzzo - the ENV vars aren't set in the webapp in staging but are for sidekiq. Is that correct?

@neilkidd can you double check please?

**Review by neilkidd — APPROVED** [review]
LBTM

**Pull request merged**
